### PR TITLE
Bump NetData Helm Chart from v1.21.1 => v1.22.1

### PR DESCRIPTION
**Pull request by Ferroin**
## BACKGROUND
* Updates Netdata to [v1.22.1](https://github.com/netdata/netdata/releases/tag/v1.22.1)

## Changes
* Bumps the Hemlchart from `v1.21.2` to `v1.22.1`
 
## Checklist
* [x]  review the [contributing doc](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md) with steps for both adding or updating your application (if applicable)
 
Reviewer: @marketplace-eng

----

This intentionally supersedes #121 as the v1.22.0 Docker images have serious usability issues.

### CODE REVIEW

**Comment by paulanunda** [comment]
Hi @Ferroin, thanks for the PR. One last change and this should be good to ship.

1. update `SRC_VERSION` to `"1.1.16"` in `stacks/netdata/render.sh`
2. Run `./stacks/netdata/render.sh` to generate your new YAML and push it up. You'll need Helm 3 to be installed on your system.

**Comment by prologic** [comment]
> Hi @Ferroin, thanks for the PR. One last change and this should be good to ship.
> 
> 1. update `SRC_VERSION` to `"1.1.16"` in `stacks/netdata/render.sh`
> 2. Run `./stacks/netdata/render.sh` to generate your new YAML and push it up. You'll need Helm 3 to be installed on your system.

Is this a new thing? We largely have automated updating the Hemlchart(s) herein for us so I'll need to update our tooling in that case?

**Comment by prologic** [comment]
Made the changes requested.

**Comment by paulanunda** [comment]
@prologic nope, its actually the old way of doing things. We're currently in the process of migrating our internal tooling to use Helm 3, so upgrades going forward will be much simpler.

**Comment by prologic** [comment]
I assume the CI check failure is expected becuase GHA doesn't share secrets from forks.

**Pull request merged**
