### PR TITLE
upgraded nginx ingress controller to latest

### PR DESCRIPTION
**Pull request by caquillo07**
## BACKGROUND
* Add information about the background and reason for the change.

-----------------------------------------------------------------------

## Changes
* List the changes that you made

-----------------------------------------------------------------------

## Checklist
- [ ] review the [contributing doc](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md) with steps for both adding or updating your application (if applicable)
------------------------------------------------------------------------

Reviewer: @marketplace-eng

### CODE REVIEW

**Comment by arosales** [comment]
It looks like PR updates:
 controller = v1.2.0-beta.1
 chart = 4.1.0-beta.1
 
 @caquillo07 can you confirm successful testing?

**Review by keladhruv — APPROVED** [review]

**Comment by caquillo07** [comment]
> It looks like PR updates: controller = v1.2.0-beta.1 chart = 4.1.0-beta.1
> 
> @caquillo07 can you confirm successful testing?

@arosales verified installing is working as expexted
```shell
➜  marketplace-kubernetes git:(upgrading-ingress-nginx) k get all -n ingress-nginx
NAME                                            READY   STATUS    RESTARTS   AGE
pod/ingress-nginx-controller-6dfc867bcb-c5ksg   1/1     Running   0          12m
pod/ingress-nginx-controller-6dfc867bcb-g4gxc   1/1     Running   0          12m

NAME                                         TYPE           CLUSTER-IP       EXTERNAL-IP       PORT(S)                      AGE
service/ingress-nginx-controller             LoadBalancer   10.245.199.60    143.244.202.246   80:31172/TCP,443:30192/TCP   12m
service/ingress-nginx-controller-admission   ClusterIP      10.245.120.183   <none>            443/TCP                      12m
service/ingress-nginx-controller-metrics     ClusterIP      10.245.184.45    <none>            10254/TCP                    12m

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ingress-nginx-controller   2/2     2            2           12m

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/ingress-nginx-controller-6dfc867bcb   2         2         2       12m
```

**Comment by caquillo07** [comment]
> It looks like PR updates: controller = v1.2.0-beta.1 chart = 4.1.0-beta.1
> 
> @caquillo07 can you confirm successful testing?

@arosales verified installing is working as expexted
```shell
➜  marketplace-kubernetes git:(upgrading-ingress-nginx) k get all -n ingress-nginx
NAME                                            READY   STATUS    RESTARTS   AGE
pod/ingress-nginx-controller-6dfc867bcb-c5ksg   1/1     Running   0          12m
pod/ingress-nginx-controller-6dfc867bcb-g4gxc   1/1     Running   0          12m

NAME                                         TYPE           CLUSTER-IP       EXTERNAL-IP       PORT(S)                      AGE
service/ingress-nginx-controller             LoadBalancer   10.245.199.60    143.244.202.246   80:31172/TCP,443:30192/TCP   12m
service/ingress-nginx-controller-admission   ClusterIP      10.245.120.183   <none>            443/TCP                      12m
service/ingress-nginx-controller-metrics     ClusterIP      10.245.184.45    <none>            10254/TCP                    12m

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ingress-nginx-controller   2/2     2            2           12m

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/ingress-nginx-controller-6dfc867bcb   2         2         2       12m
```

**Review by arosales — APPROVED** [review]
Thanks for confirming successful testing, and updating the versions.

**Pull request merged**
