### PR TITLE
Bump OpenEBS Helm Chart from v1.10.0 to v.2.6.0

### PR DESCRIPTION
**Pull request by muratkars**
## BACKGROUND
- Updated OpenEBS version to the latest v2.6.0

## Changes
- Migrated from depreciated stable/openebs chart to the official OpenEBS chart location

Signed-off-by: Murat Karslioglu <murat@mayadata.io>

Reviewer: @marketplace-eng

### CODE REVIEW

**Review by amilcaru123 — APPROVED** [review]

**Comment by pachamaltese** [comment]
Part 1 of review:

```
pacha@pop-os:~/github$ PRNUMBER=203
pacha@pop-os:~/github$ SOFTWARE='openebs'
pacha@pop-os:~/github$ git clone git@github.com:digitalocean/marketplace-kubernetes.git
Cloning into 'marketplace-kubernetes'...
remote: Enumerating objects: 128, done.
remote: Counting objects: 100% (128/128), done.
remote: Compressing objects: 100% (100/100), done.
remote: Total 3212 (delta 54), reused 69 (delta 18), pack-reused 3084
Receiving objects: 100% (3212/3212), 1.76 MiB | 1.64 MiB/s, done.
Resolving deltas: 100% (1726/1726), done.
pacha@pop-os:~/github$ cd  ~/github/marketplace-kubernetes
pacha@pop-os:~/github/marketplace-kubernetes$ git fetch origin pull/$PRNUMBER/head:$PRNUMBER && git checkout $PRNUMBER

remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 5 (delta 2), reused 5 (delta 2), pack-reused 0
Unpacking objects: 100% (5/5), 920 bytes | 230.00 KiB/s, done.
From github.com:digitalocean/marketplace-kubernetes
 * [new ref]         refs/pull/203/head -> 203
Switched to branch '203'
pacha@pop-os:~/github/marketplace-kubernetes$ 
pacha@pop-os:~/github/marketplace-kubernetes$ cd stacks/$SOFTWARE
pacha@pop-os:~/github/marketplace-kubernetes/stacks/openebs$ doctl kubernetes cluster kubeconfig save 1b8272ba-1291-49c6-a14a-f4471ec3773a
Notice: Adding cluster credentials to kubeconfig file found in "/home/pacha/.kube/config"
Notice: Setting current-context to do-sfo2-k8s-1-20-2-do-0-sfo2-1615998210053
pacha@pop-os:~/github/marketplace-kubernetes/stacks/openebs$ ./deploy.sh
"openebs" already exists with the same configuration, skipping
Error: Kubernetes cluster unreachable: Get "https://1b8272ba-1291-49c6-a14a-f4471ec3773a.k8s.ondigitalocean.com/version?timeout=32s": dial tcp 159.65.106.23:443: connect: connection refused
pacha@pop-os:~/github/marketplace-kubernetes/stacks/openebs$ ./deploy.sh
"openebs" already exists with the same configuration, skipping
Release "openebs" does not exist. Installing it now.
NAME: openebs
LAST DEPLOYED: Wed Mar 17 13:46:19 2021
NAMESPACE: openebs
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
The OpenEBS has been installed. Check its status by running:
$ kubectl get pods -n openebs

For dynamically creating OpenEBS Volumes, you can either create a new StorageClass or
use one of the default storage classes provided by OpenEBS.

Use `kubectl get sc` to see the list of installed OpenEBS StorageClasses. A sample
PVC spec using `openebs-jiva-default` StorageClass is given below:"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-vol-claim
spec:
  storageClassName: openebs-jiva-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
---

Please note that, OpenEBS uses iSCSI for connecting applications with the
OpenEBS Volumes and your nodes should have the iSCSI initiator installed.

For more information, visit our Slack at https://openebs.io/community or view the documentation online at http://docs.openebs.io/.
```

**Comment by pachamaltese** [comment]
Part 2 of review:

```
$ kubectl get pods -A
NAMESPACE     NAME                                          READY   STATUS    RESTARTS   AGE
kube-system   cilium-2t9m5                                  1/1     Running   0          34m
kube-system   cilium-fhxh2                                  1/1     Running   0          34m
kube-system   cilium-gn9cc                                  1/1     Running   0          34m
kube-system   cilium-operator-84bdd6f7b6-rmj7s              1/1     Running   0          36m
kube-system   cilium-operator-84bdd6f7b6-vr8sg              1/1     Running   0          36m
kube-system   coredns-55ff57f948-6jrd8                      1/1     Running   0          36m
kube-system   coredns-55ff57f948-c9m5b                      1/1     Running   0          36m
kube-system   csi-do-node-h4jb4                             2/2     Running   0          34m
kube-system   csi-do-node-pdz6t                             2/2     Running   0          34m
kube-system   csi-do-node-vzb7g                             2/2     Running   0          34m
kube-system   do-node-agent-4wqqs                           1/1     Running   0          34m
kube-system   do-node-agent-cbcp4                           1/1     Running   0          34m
kube-system   do-node-agent-r9s6v                           1/1     Running   0          34m
kube-system   kube-proxy-2dwpd                              1/1     Running   0          34m
kube-system   kube-proxy-c5smj                              1/1     Running   0          34m
kube-system   kube-proxy-m64zj                              1/1     Running   0          34m
openebs       openebs-admission-server-79f9f888d7-jbpn5     1/1     Running   0          18m
openebs       openebs-apiserver-59d979b7f6-wb5t8            1/1     Running   2          18m
openebs       openebs-localpv-provisioner-d9786794d-xjc8k   1/1     Running   0          18m
openebs       openebs-ndm-operator-55d7c755d5-gpvrq         1/1     Running   0          18m
openebs       openebs-ndm-qj85x                             1/1     Running   0          18m
openebs       openebs-ndm-qmt2m                             1/1     Running   0          18m
openebs       openebs-ndm-wqndz                             1/1     Running   0          18m
openebs       openebs-provisioner-694bd9755c-h2qpm          1/1     Running   0          18m
openebs       openebs-snapshot-operator-7b886dccdb-btnww    2/2     Running   0          18m
```

```
$ clear && kubectl get csr
$ kubectl get pods -A
NAMESPACE     NAME                                          READY   STATUS    RESTARTS   AGE
kube-system   cilium-2t9m5                                  1/1     Running   0          34m
kube-system   cilium-fhxh2                                  1/1     Running   0          34m
kube-system   cilium-gn9cc                                  1/1     Running   0          34m
kube-system   cilium-operator-84bdd6f7b6-rmj7s              1/1     Running   0          36m
kube-system   cilium-operator-84bdd6f7b6-vr8sg              1/1     Running   0          36m
kube-system   coredns-55ff57f948-6jrd8                      1/1     Running   0          36m
kube-system   coredns-55ff57f948-c9m5b                      1/1     Running   0          36m
kube-system   csi-do-node-h4jb4                             2/2     Running   0          34m
kube-system   csi-do-node-pdz6t                             2/2     Running   0          34m
kube-system   csi-do-node-vzb7g                             2/2     Running   0          34m
kube-system   do-node-agent-4wqqs                           1/1     Running   0          34m
kube-system   do-node-agent-cbcp4                           1/1     Running   0          34m
kube-system   do-node-agent-r9s6v                           1/1     Running   0          34m
kube-system   kube-proxy-2dwpd                              1/1     Running   0          34m
kube-system   kube-proxy-c5smj                              1/1     Running   0          34m
kube-system   kube-proxy-m64zj                              1/1     Running   0          34m
openebs       openebs-admission-server-79f9f888d7-jbpn5     1/1     Running   0          18m
openebs       openebs-apiserver-59d979b7f6-wb5t8            1/1     Running   2          18m
openebs       openebs-localpv-provisioner-d9786794d-xjc8k   1/1     Running   0          18m
openebs       openebs-ndm-operator-55d7c755d5-gpvrq         1/1     Running   0          18m
openebs       openebs-ndm-qj85x                             1/1     Running   0          18m
openebs       openebs-ndm-qmt2m                             1/1     Running   0          18m
openebs       openebs-ndm-wqndz                             1/1     Running   0          18m
openebs       openebs-provisioner-694bd9755c-h2qpm          1/1     Running   0          18m
openebs       openebs-snapshot-operator-7b886dccdb-btnww    2/2     Running   0          18m
```

**Comment by pachamaltese** [comment]
This is working without problem and can be merged.

**Review by pachamaltese — APPROVED** [review]
all the checks and details are in the comments

**Pull request merged**
