### PR TITLE
fusionauth-second-pr

### PR DESCRIPTION
**Pull request by jaywood128**
## BACKGROUND
* The original Bitnami PostgreSQL helm chart used Postres15, which had breaking changes. We also need a way to handle our db user and root user password more efficiently. 

-----------------------------------------------------------------------

## Changes
* Update `bitnami/postgresql` to Postgresql 14 - Postgresql 15 had breaking changes
* Updated README to reflect LoadBalancer service changes
* Use Kubernetes secrets to set db user password and db root user password on upgrade

-----------------------------------------------------------------------

## Checklist
- [x] review the [contributing doc](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md) with steps for both adding or updating your application (if applicable)
------------------------------------------------------------------------

Reviewer: @marketplace-eng

### CODE REVIEW

**Comment by scott** [comment]
Hey @jaywood128 thanks for providing this updated chart.  When I test it by running `./deploy.sh` am getting the following error:
```
Error: execution error at (fusionauth/templates/secret.yaml:4:15): A password for your database is required!
```

**Comment by mmanes** [comment]
@scott Are you running `deploy.sh` from a Mac? The stock `tr` on MacOS doesn't work with our random password generator, but I don't believe this will be an issue when deploying through the marketplace.

**Review by scott — APPROVED** [review]
LGTM 👍

**Comment by jaywood128** [comment]
@scott can you suggest a way to debug a failing install? I installed FusionAuth on a Digital Ocean Kubernetes cluster and I could not find anything meaningful errors in the logs. Is there a way for you to run it on your end and see more meaningful logs?

**Comment by mmanes** [comment]
It would be nice to have a mechanism to view the output of the scripts, but I think the issue here is that we're not determining the full path to `search-values.yaml` at runtime. We should be able to get a new PR out shortly.

**Pull request merged**
