### PR TITLE
Add Karvdash stack

### PR DESCRIPTION
**Pull request by chazapis**
## BACKGROUND

[Karvdash](https://github.com/CARV-ICS-FORTH/karvdash) is a dashboard service for facilitating data science on Kubernetes. It supplies the landing page for users, allowing them to launch notebooks and other services, design workflows, and specify parameters related to execution through a user-friendly interface. Karvdash manages users, wires up relevant storage to the appropriate paths inside running containers, securely provisions multiple services under one externally-accessible HTTPS endpoint, while keeping them isolated in per-user namespaces at the Kubernetes level, and provides an identity service for OAuth 2.0/OIDC-compatible applications.

This stack installs Karvdash, along with respective dependencies and associated software as a one click-application in DigitalOcean Kubernetes. Upon deployment, users have web-based access to a full-featured software stack, which includes [JupyterHub](https://jupyter.org/hub), [Argo Workflows](https://argoproj.github.io/workflows), as well as [Datashim](https://github.com/datashim-io/datashim) to automatically connect notebooks, workflow and service containers to storage backed by DigitalOcean Spaces.

-----------------------------------------------------------------------

## Changes
* Initial version, based on Karvdash v3.0.1

-----------------------------------------------------------------------

## Checklist
- [x] review the [contributing doc](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md) with steps for both adding or updating your application (if applicable)
------------------------------------------------------------------------

Reviewer: @marketplace-eng

### CODE REVIEW

**Review by keladhruv — CHANGES_REQUESTED** [review]
Hi @chazapis!
Than you for your PR! Karvdash will be a great addition to the DigitalOcean Marketplace.

I get the following error while running deploy.sh -
`Error: looks like "https://charts.jetstack.io" is not a valid chart repository or cannot be reached: Get https://charts.jetstack.io/index.yaml: dial tcp: lookup charts.jetstack.io: no such host`

Please have a look at it.

Thanks

**Comment by chazapis** [comment]
Hello @keladhruv!
I am also very exited to have Karvdash available in the DigitalOcean Marketplace!

According to the [cert-manager installation instructions](https://cert-manager.io/docs/installation/helm/), they still use this Helm repo. It looks like whatever caused the issue has been resolved:
```
$ helm repo add jetstack https://charts.jetstack.io
"jetstack" has been added to your repositories
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "jetstack" chart repository
Update Complete. ⎈Happy Helming!⎈
$ 
```

**Comment by keladhruv** [comment]
Thanks for getting back, the issue with jetstack have been fixed.
I am facing an error here -
`WARNING: The cert-manager webhook is not ready... Retrying in 5 seconds... (attempt 1/5)
./deploy.sh: line 81: envsubst: command not found
error: no objects passed to apply
WARNING: The cert-manager webhook is not ready... Retrying in 5 seconds... (attempt 2/5)
./deploy.sh: line 81: envsubst: command not found
error: no objects passed to apply
WARNING: The cert-manager webhook is not ready... Retrying in 5 seconds... (attempt 3/5)
./deploy.sh: line 81: envsubst: command not found
error: no objects passed to apply
WARNING: The cert-manager webhook is not ready... Retrying in 5 seconds... (attempt 4/5)
./deploy.sh: line 81: envsubst: command not found
error: no objects passed to apply
WARNING: The cert-manager webhook is not ready... Retrying in 5 seconds... (attempt 5/5)
ERROR: The cert-manager webhook failed to initialize after 5 attempts.`

I am running this on a clean fresh cluster.

**Comment by chazapis** [comment]
Fixed. I was using the `envsubst` utility to substitute variables in a YAML file before applying it. Now I just use `sed`, which should be available.

As a side note, you should probably add to the [contributing doc](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md) some reference VM or container that can be used to test `deploy.sh`. That would address any questions regarding the binaries available (and associated versions) when `deploy.sh` runs.

**Comment by keladhruv** [comment]
Thanks for the feedback, we will update the contributing.md document.

While I was able to install Karvdash, it still fails at the following. 
```
Your release is named karvdash and will be available at https://138.197.229.54.nip.io in a few moments.
Release "jupyterhub" does not exist. Installing it now.
Error: parse error at (jupyterhub/templates/hub/_helpers-passwords.tpl:35): function "dig" not defined
```

**Comment by chazapis** [comment]
@keladhruv, the JupyterHub chart requires Helm >= 3.5. This issue has been documented (here)[https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2234]. Is it possible to upgrade Helm in your environment?

**Comment by keladhruv** [comment]
I have updated the helm version and the installation works. We are excited to add Karvdash to DigitalOcean.

Once the PR is merged, Please update the app details in Vendor Portal for Karvdash to be listed.

**Review by keladhruv — APPROVED** [review]

**Pull request merged**
