### PR TITLE
Bump op-scim-bridge helm charts to v1.4.3

### PR DESCRIPTION
**Pull request by kvincent2**
## BACKGROUND
Releasing version 1.4.3 of the 1Password SCIM Bridge

-----------------------------------------------------------------------

## Changes
Releasing version 1.4.3 of the 1Password SCIM Bridge

-----------------------------------------------------------------------

## Checklist
- [x] review the [contributing doc](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md) with steps for both adding or updating your application (if applicable)
------------------------------------------------------------------------

Please note that we are in the process of upgrading our helm charts to helm 3, but we have a few more dependencies to take care of on our side before that is possible. Please expect the upgrade in the near future.

Reviewer: @marketplace-eng

### CODE REVIEW

**Comment by grellyd** [comment]
@paulanunda We seem to keep re-adding all our previous commits. What are we doing wrong here?

Our upgrade flow so far has been:
 - Pull the `digitalocean/marketplace-kubernetes` fork's changes down to a branch off our fork
 - Merge them into master of our fork
 - Update our application on a branch
 - Merge them into master of our fork.
 - Open a PR on `digitalocean/marketplace-kubernetes` with our changes from our master.

I would expect to see just the merge commit updating from upstream plus our new update commits and merge requests. Instead I see many old commits. 

Any insight?

Screenshot 2020-07-15 at 4 44 07 PM

**Comment by grellyd** [comment]
@paulanunda we are working to have it hosted at our 1Password Github in a new repo. It will be something along the lines of `https://github.com/1password/op-scim-helm` 

We are working with our ops team to make that a reality. Once that is complete, and we do the repo conversion, then we will submit with the Helm v3 chart for the next update.

**Comment by paulanunda** [comment]
@grellyd sounds good. As far as your initial issue goes (https://github.com/digitalocean/marketplace-kubernetes/pull/146#issuecomment-659071714), I suspect it has to do w/ the fact that I do a squash-merge whenever merging PRs. If you're merging instead of rebasing upstream changes into your fork, that may be what's causing your issue. The simplest thing to do may be to just re-create your fork, and proceed from there.

**Comment by grellyd** [comment]
I understand @paulanunda; that makes perfect sense. Thanks for the insight! We will fix that on our end for the next release.

**Comment by grellyd** [comment]
Please let us know if anything needs to be changed for this version bump.

**Pull request merged**
