### PR TITLE
Add PostHog to DigitalOcean Marketplace for Kubernetes

### PR DESCRIPTION
**Pull request by fuziontech**
## BACKGROUND

New submission to the marketplace!

-----------------------------------------------------------------------

## Changes
* Add default values for DigitalOcean to stack
* Add README for deploying
* add deploy.sh

-----------------------------------------------------------------------

## Checklist
- [x] review the [contributing doc](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md) with steps for both adding or updating your application (if applicable)
------------------------------------------------------------------------

Reviewer: @marketplace-eng

### CODE REVIEW

**Comment by macobo** [comment]
cc @keladhruv any chance to get this reviewed?

**Comment by keladhruv** [comment]
Thanks for the PR @fuziontech!
When I  run the `deploy.sh` script, the posthog installation fails.

Cluster details -  3x(8cpu16gb node)

Last point of failure  -
```
wait.go:206: [debug] Service does not have load balancer ingress IP address: posthog/posthog-ingress-nginx-controller
```

**Comment by fuziontech** [comment]
@keladhruv Give it another try now! Had to bump the chart version for a bug fix and set timeout

**Review by keladhruv — APPROVED** [review]
LGTM

**Comment by keladhruv** [comment]
@fuziontech @macobo 
Your PR is now merged,  please update the version on [vendor portal](https://cloud.digitalocean.com/vendorportal/) so that your changes get reflected on [DigitalOcean Marketplace](https://marketplace.digitalocean.com/apps/1password-scim-bridge)

**Pull request merged**
