### PR TITLE
Add stack for CloudCasa to marketplace

### PR DESCRIPTION
**Pull request by bobadair**
## BACKGROUND

This is our initial PR for adding a [CloudCasa](https://cloudcasa.io/) stack to the marketplace. It uses a Helm 3 chart to install the CloudCasa agent on Kubernetes.

-----------------------------------------------------------------------

## Changes

Contains deploy.sh, values.yml, and README.md.

-----------------------------------------------------------------------

## Checklist
- [x] review the [contributing doc](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md) with steps for both adding or updating your application (if applicable)
------------------------------------------------------------------------

Reviewer: @marketplace-eng

### CODE REVIEW

**Comment by pachamaltese** [comment]
@bobadair Hi! I get the following error:
```
"cloudcasa-helmchart" already exists with the same configuration, skipping
Release "cloudcasa" does not exist. Installing it now.
W0311 18:01:15.359734  163729 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "volumesnapshotclasses.snapshot.storage.k8s.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "cloudcasa"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"
```

were you able to run `deploy.sh` successfully?

**Comment by bobadair** [comment]
Thanks @pachamaltese. I believe we were, but @nitishdsharma is actually the person to ask about this.

**Comment by pachamaltese** [comment]
@nitishdsharma Hi. I haven't received a reply in 7 days so I'm closing this ticket for now. I can reopen it later.

**Comment by bobadair** [comment]
Thanks @pachamaltese. We are testing a change to fix this. Will update this PR when it is ready.

**Comment by nitishdsharma** [comment]
@pachamaltese 
We have made the changes in our helmchart code, no change in the PR is required. Can you pls refer the same PR to test the Cloudcasa helmchart.

Thanks.

**Comment by bobadair** [comment]
Hi @pachamaltese. Can you please re-open this PR? Now that our Helm chart has been updated, we believe the issue you ran in to should be fixed.

**Comment by pachamaltese** [comment]
hi @bobadair 
sorry for the slow reply, I've created a ticket manually for this

**Review by pachamaltese — APPROVED** [review]
it works well, I was able to create and instance and deploy without problem
```
kubectl get pods -n cloudcasa-io
NAME                        READY   STATUS    RESTARTS   AGE
kubeagent-89cd7cb6c-rrhgq   2/2     Running   0          6m26s
```

**Comment by bobadair** [comment]
Thanks @pachamaltese!

**Comment by MattIPv4** [comment]
Hey, @bobadair - Thanks a ton for this sweet PR! 😄

Would you please shoot me an email when you get a chance?
mcowley at digitalocean dot com 🎉

**Comment by nitishdsharma** [comment]
@pachadotdev 
Hi,

Just a quick question. We intend to update this chart version to v1.0.0 from v1.0. Can we push this change for the existing chart now. It would be a great help if we can do it. I can raise a PR for the same.

Thanks.

**Pull request merged**
