### PR TITLE
Add single click application stack for Jaeger

### PR DESCRIPTION
**Pull request by annanay25**
- Added helm chart and tested on DigitalOcean Managed Kubernetes 
- Generated yaml for DigitalOcean deployment
- Added deploy instructions
- Added Jaeger logo

### CODE REVIEW

**Comment by paulanunda** [comment]
I'm getting a CrashLoopBackOff in a few of the pods:

```
NAME                                READY   STATUS             RESTARTS   AGE
jaeger-agent-9h76m                  1/1     Running            0          35m
jaeger-agent-ssjwf                  1/1     Running            0          35m
jaeger-agent-w6k6d                  1/1     Running            0          35m
jaeger-cassandra-0                  1/1     Running            0          35m
jaeger-cassandra-1                  1/1     Running            0          33m
jaeger-cassandra-2                  1/1     Running            0          32m
jaeger-collector-54cbcf8c44-p79mc   0/1     CrashLoopBackOff   11         35m
jaeger-query-5dc755dc4f-x9zlg       1/2     CrashLoopBackOff   11         35m
```

this is running on a 6vpu/16gb-per-node, 3-node cluster

**Comment by paulanunda** [comment]
```
jaeger git:pr/67 ❯ k logs jaeger-query-5dc755dc4f-x9zlg -c jaeger-query                                                                                                                                   ⏎
2019/11/14 20:33:15 maxprocs: Leaving GOMAXPROCS=6: CPU quota undefined
{"level":"info","ts":1573763595.8453438,"caller":"flags/service.go:115","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1573763595.8457685,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1573763595.845859,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":16687}
{"level":"info","ts":1573763595.8459046,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":16687,"health-status":"unavailable"}
2019/11/14 20:33:15 error: failed to connect to 10.244.1.240:9042 due to error: Keyspace 'jaeger_v1_dc1' does not exist
2019/11/14 20:33:16 error: failed to connect to 10.244.2.184:9042 due to error: Keyspace 'jaeger_v1_dc1' does not exist
2019/11/14 20:33:16 error: failed to connect to 10.244.1.240:9042 due to error: Keyspace 'jaeger_v1_dc1' does not exist
2019/11/14 20:33:16 error: failed to connect to 10.244.0.153:9042 due to error: Keyspace 'jaeger_v1_dc1' does not exist
{"level":"fatal","ts":1573763596.284178,"caller":"query/main.go:88","msg":"Failed to init storage factory","error":"no connections were made when creating the session","stacktrace":"main.main.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/query/main.go:88\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:762\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:852\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:800\nmain.main\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/query/main.go:130\nruntime.main\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/proc.go:200"}
```

```
jaeger git:pr/67 ❯ k logs jaeger-query-5dc755dc4f-x9zlg -c jaeger-agent-sidecar
2019/11/14 19:56:37 maxprocs: Leaving GOMAXPROCS=6: CPU quota undefined
{"level":"info","ts":1573761397.0358043,"caller":"flags/service.go:115","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1573761397.036007,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1573761397.036058,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":14271}
{"level":"info","ts":1573761397.0360746,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":14271,"health-status":"unavailable"}
{"level":"info","ts":1573761397.037073,"caller":"grpc/builder.go:108","msg":"Agent requested insecure grpc connection to collector(s)"}
{"level":"info","ts":1573761397.0371044,"caller":"grpc/clientconn.go:242","msg":"parsed scheme: \"\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761397.0371256,"caller":"grpc/clientconn.go:248","msg":"scheme \"\" not registered, fallback to default scheme","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761397.0371432,"caller":"grpc/resolver_conn_wrapper.go:113","msg":"ccResolverWrapper: sending update to cc: {[{jaeger-collector:14250 0  <nil>}] }","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761397.037376,"caller":"base/balancer.go:76","msg":"base.baseBalancer: got new resolver state: {[{jaeger-collector:14250 0  <nil>}] }","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761397.0374734,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761397.038358,"caller":"agent/main.go:75","msg":"Starting agent"}
{"level":"info","ts":1573761397.0384073,"caller":"healthcheck/handler.go:130","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1573761397.0385401,"caller":"app/agent.go:69","msg":"Starting jaeger-agent HTTP server","http-port":5778}
{"level":"info","ts":1573761417.0378222,"caller":"grpc/clientconn.go:1139","msg":"grpc: addrConn.createTransport failed to connect to {jaeger-collector:14250 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 10.245.9.114:14250: i/o timeout\". Reconnecting...","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761417.037949,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, TRANSIENT_FAILURE","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761418.038195,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761418.038263,"caller":"roundrobin/roundrobin.go:50","msg":"roundrobinPicker: newPicker called with readySCs: map[]","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761438.0384507,"caller":"grpc/clientconn.go:1139","msg":"grpc: addrConn.createTransport failed to connect to {jaeger-collector:14250 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 10.245.9.114:14250: i/o timeout\". Reconnecting...","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761438.0385523,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, TRANSIENT_FAILURE","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761439.6758103,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761439.675884,"caller":"roundrobin/roundrobin.go:50","msg":"roundrobinPicker: newPicker called with readySCs: map[]","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761459.6760623,"caller":"grpc/clientconn.go:1139","msg":"grpc: addrConn.createTransport failed to connect to {jaeger-collector:14250 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 10.245.9.114:14250: i/o timeout\". Reconnecting...","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761459.6762183,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, TRANSIENT_FAILURE","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761462.183939,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761462.184029,"caller":"roundrobin/roundrobin.go:50","msg":"roundrobinPicker: newPicker called with readySCs: map[]","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761482.1840467,"caller":"grpc/clientconn.go:1139","msg":"grpc: addrConn.createTransport failed to connect to {jaeger-collector:14250 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 10.245.9.114:14250: i/o timeout\". Reconnecting...","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761482.1841993,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, TRANSIENT_FAILURE","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761485.7426198,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761485.7426772,"caller":"roundrobin/roundrobin.go:50","msg":"roundrobinPicker: newPicker called with readySCs: map[]","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761505.7428217,"caller":"grpc/clientconn.go:1139","msg":"grpc: addrConn.createTransport failed to connect to {jaeger-collector:14250 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 10.245.9.114:14250: i/o timeout\". Reconnecting...","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761505.7453027,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, TRANSIENT_FAILURE","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761512.0870998,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761512.0871756,"caller":"roundrobin/roundrobin.go:50","msg":"roundrobinPicker: newPicker called with readySCs: map[]","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761532.0872953,"caller":"grpc/clientconn.go:1139","msg":"grpc: addrConn.createTransport failed to connect to {jaeger-collector:14250 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 10.245.9.114:14250: i/o timeout\". Reconnecting...","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761532.0874028,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, TRANSIENT_FAILURE","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761542.8308954,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761542.830962,"caller":"roundrobin/roundrobin.go:50","msg":"roundrobinPicker: newPicker called with readySCs: map[]","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761562.8312316,"caller":"grpc/clientconn.go:1139","msg":"grpc: addrConn.createTransport failed to connect to {jaeger-collector:14250 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 10.245.9.114:14250: i/o timeout\". Reconnecting...","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761562.8313348,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, TRANSIENT_FAILURE","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761578.0781856,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761578.0782905,"caller":"roundrobin/roundrobin.go:50","msg":"roundrobinPicker: newPicker called with readySCs: map[]","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761607.3832457,"caller":"grpc/clientconn.go:1139","msg":"grpc: addrConn.createTransport failed to connect to {jaeger-collector:14250 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 10.245.9.114:14250: i/o timeout\". Reconnecting...","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761607.3833735,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, TRANSIENT_FAILURE","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761636.6884098,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761636.6884794,"caller":"roundrobin/roundrobin.go:50","msg":"roundrobinPicker: newPicker called with readySCs: map[]","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761675.2876172,"caller":"grpc/clientconn.go:1139","msg":"grpc: addrConn.createTransport failed to connect to {jaeger-collector:14250 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 10.245.9.114:14250: i/o timeout\". Reconnecting...","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761675.288035,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, TRANSIENT_FAILURE","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761713.8872545,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761713.8873339,"caller":"roundrobin/roundrobin.go:50","msg":"roundrobinPicker: newPicker called with readySCs: map[]","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761782.6366575,"caller":"grpc/clientconn.go:1139","msg":"grpc: addrConn.createTransport failed to connect to {jaeger-collector:14250 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 10.245.9.114:14250: i/o timeout\". Reconnecting...","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761782.6367457,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, TRANSIENT_FAILURE","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761851.386232,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761851.3863072,"caller":"roundrobin/roundrobin.go:50","msg":"roundrobinPicker: newPicker called with readySCs: map[]","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761966.1221044,"caller":"grpc/clientconn.go:1139","msg":"grpc: addrConn.createTransport failed to connect to {jaeger-collector:14250 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 10.245.9.114:14250: i/o timeout\". Reconnecting...","system":"grpc","grpc_log":true}
{"level":"info","ts":1573761966.1221945,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, TRANSIENT_FAILURE","system":"grpc","grpc_log":true}
{"level":"info","ts":1573762080.8580966,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1573762080.8581583,"caller":"roundrobin/roundrobin.go:50","msg":"roundrobinPicker: newPicker called with readySCs: map[]","system":"grpc","grpc_log":true}
{"level":"info","ts":1573762205.57469,"caller":"grpc/clientconn.go:1139","msg":"grpc: addrConn.createTransport failed to connect to {jaeger-collector:14250 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 10.245.9.114:14250: i/o timeout\". Reconnecting...","system":"grpc","grpc_log":true}
{"level":"info","ts":1573762205.5747573,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, TRANSIENT_FAILURE","system":"grpc","grpc_log":true}
{"level":"info","ts":1573762330.2914462,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1573762330.2915359,"caller":"roundrobin/roundrobin.go:50","msg":"roundrobinPicker: newPicker called with readySCs: map[]","system":"grpc","grpc_log":true}
{"level":"info","ts":1573762455.96408,"caller":"grpc/clientconn.go:1139","msg":"grpc: addrConn.createTransport failed to connect to {jaeger-collector:14250 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 10.245.9.114:14250: i/o timeout\". Reconnecting...","system":"grpc","grpc_log":true}
{"level":"info","ts":1573762455.964161,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, TRANSIENT_FAILURE","system":"grpc","grpc_log":true}
{"level":"info","ts":1573762581.6368392,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1573762581.6369002,"caller":"roundrobin/roundrobin.go:50","msg":"roundrobinPicker: newPicker called with readySCs: map[]","system":"grpc","grpc_log":true}
{"level":"info","ts":1573762684.5183234,"caller":"grpc/clientconn.go:1139","msg":"grpc: addrConn.createTransport failed to connect to {jaeger-collector:14250 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 10.245.9.114:14250: i/o timeout\". Reconnecting...","system":"grpc","grpc_log":true}
{"level":"info","ts":1573762684.5184495,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, TRANSIENT_FAILURE","system":"grpc","grpc_log":true}
{"level":"info","ts":1573762787.3998258,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1573762787.3999028,"caller":"roundrobin/roundrobin.go:50","msg":"roundrobinPicker: newPicker called with readySCs: map[]","system":"grpc","grpc_log":true}
{"level":"info","ts":1573762914.6985068,"caller":"grpc/clientconn.go:1139","msg":"grpc: addrConn.createTransport failed to connect to {jaeger-collector:14250 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 10.245.9.114:14250: i/o timeout\". Reconnecting...","system":"grpc","grpc_log":true}
{"level":"info","ts":1573762914.69864,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, TRANSIENT_FAILURE","system":"grpc","grpc_log":true}
{"level":"info","ts":1573763041.9977846,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1573763041.9979446,"caller":"roundrobin/roundrobin.go:50","msg":"roundrobinPicker: newPicker called with readySCs: map[]","system":"grpc","grpc_log":true}
{"level":"info","ts":1573763172.6277592,"caller":"grpc/clientconn.go:1139","msg":"grpc: addrConn.createTransport failed to connect to {jaeger-collector:14250 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 10.245.9.114:14250: connect: connection timed out\". Reconnecting...","system":"grpc","grpc_log":true}
{"level":"info","ts":1573763172.627895,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, TRANSIENT_FAILURE","system":"grpc","grpc_log":true}
{"level":"info","ts":1573763305.9218574,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1573763305.9219375,"caller":"roundrobin/roundrobin.go:50","msg":"roundrobinPicker: newPicker called with readySCs: map[]","system":"grpc","grpc_log":true}
{"level":"info","ts":1573763415.2045906,"caller":"grpc/clientconn.go:1139","msg":"grpc: addrConn.createTransport failed to connect to {jaeger-collector:14250 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 10.245.9.114:14250: i/o timeout\". Reconnecting...","system":"grpc","grpc_log":true}
{"level":"info","ts":1573763415.2046916,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, TRANSIENT_FAILURE","system":"grpc","grpc_log":true}
{"level":"info","ts":1573763524.4874315,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1573763524.4875057,"caller":"roundrobin/roundrobin.go:50","msg":"roundrobinPicker: newPicker called with readySCs: map[]","system":"grpc","grpc_log":true}
{"level":"info","ts":1573763646.2160983,"caller":"grpc/clientconn.go:1139","msg":"grpc: addrConn.createTransport failed to connect to {jaeger-collector:14250 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 10.245.9.114:14250: i/o timeout\". Reconnecting...","system":"grpc","grpc_log":true}
{"level":"info","ts":1573763646.216182,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc0001f8080, TRANSIENT_FAILURE","system":"grpc","grpc_log":true}
```

**Comment by paulanunda** [comment]
```
jaeger git:pr/67 ❯ k logs jaeger-collector-54cbcf8c44-p79mc
2019/11/14 20:32:44 maxprocs: Leaving GOMAXPROCS=6: CPU quota undefined
{"level":"info","ts":1573763564.566367,"caller":"flags/service.go:115","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1573763564.56694,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1573763564.5671906,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":14269}
{"level":"info","ts":1573763564.5672376,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":14269,"health-status":"unavailable"}
2019/11/14 20:32:44 error: failed to connect to 10.244.0.153:9042 due to error: Keyspace 'jaeger_v1_dc1' does not exist
2019/11/14 20:32:44 error: failed to connect to 10.244.2.184:9042 due to error: Keyspace 'jaeger_v1_dc1' does not exist
2019/11/14 20:32:44 error: failed to connect to 10.244.1.240:9042 due to error: Keyspace 'jaeger_v1_dc1' does not exist
2019/11/14 20:32:44 error: failed to connect to 10.244.0.153:9042 due to error: Keyspace 'jaeger_v1_dc1' does not exist
{"level":"fatal","ts":1573763564.9669554,"caller":"collector/main.go:91","msg":"Failed to init storage factory","error":"no connections were made when creating the session","stacktrace":"main.main.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/main.go:91\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:762\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:852\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:800\nmain.main\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/main.go:182\nruntime.main\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/proc.go:200"}
```

**Comment by annanay25** [comment]
Hi @paulanunda - Thanks for taking the time to review this PR.

IIUC, the `jaeger-agent` deployment is failing because `jaeger-collector` is in `CrashLoopBackOff`, which is in-turn failing because the `jaeger-cassandra-schema` job has not run.. hence the `error: Keyspace ... does not exist`

Could you please add one more node and check if that helps with a successful deployment?

**Comment by paulanunda** [comment]
I added an additional node, totaling in 4 `4 GB RAM, 2 vCPUs` nodes, and its running, though not with much headroom.

```
marketplace-kubernetes git:pr/67 ❯ k top po -n jaeger
NAME                                CPU(cores)   MEMORY(bytes)
jaeger-agent-4m946                  1m           6Mi
jaeger-agent-6vb84                  1m           6Mi
jaeger-agent-cfk9z                  1m           6Mi
jaeger-agent-tlzhj                  1m           6Mi
jaeger-cassandra-0                  238m         2298Mi
jaeger-cassandra-1                  147m         2294Mi
jaeger-cassandra-2                  12m          2293Mi
jaeger-collector-54cbcf8c44-x5ttw   1m           7Mi
jaeger-query-5dc755dc4f-4glg4       1m           35Mi
```

```
marketplace-kubernetes git:pr/67 ❯ k top nodes
NAME                  CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
pool-zzc2p6n63-ajjc   498m         24%    3125Mi          100%
pool-zzc2p6n63-ajo2   148m         7%     3050Mi          98%
pool-zzc2p6n63-ajol   80m          4%     792Mi           25%
pool-zzc2p6n63-ajot   211m         10%    3060Mi          98%
```

Please specify a minimum number of nodes (4) in the readme.

**Comment by annanay25** [comment]
@paulanunda - Done.

**Comment by annanay25** [comment]
Thanks @paulanunda!

**Pull request merged**
