### PR TITLE
Update 1Password SCIM bridge to v2.3.0

### PR DESCRIPTION
**Pull request by devillexio**
## BACKGROUND
* Update the 1Password SCIM bridge version from v2.2.1 to v2.3.0.

-----------------------------------------------------------------------

## Changes
* [1Password SCIM bridge v2.3.0 changelog](https://app-updates.agilebits.com/product_history/SCIM#v203004)

-----------------------------------------------------------------------

## Checklist
- [x] review the [contributing doc](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md) with steps for both adding or updating your application (if applicable)
------------------------------------------------------------------------

Reviewer: @marketplace-eng

### CODE REVIEW

**Comment by devillexio** [comment]
Hello folks! :wave: Just wanted to follow up if you have an idea when you can look at this PR? We're hoping to make this release available to our customers this week.

**Comment by pachadotdev** [comment]
> Hello folks! wave Just wanted to follow up if you have an idea when you can look at this PR? We're hoping to make this release available to our customers this week.

Hi @paulanunda. I checked this update for my 1Password setup and it works ok. Can you merge it?

**Review by paulanunda — APPROVED** [review]
LGTM

**Comment by paulanunda** [comment]
@devillexio this change has recently started to regularly fail, could you help troubleshoot?

**Pull request merged**
