### PR TITLE
Update 1Password/op-scim-bridge to v2.5.0

### PR DESCRIPTION
**Pull request by devillexio**
## BACKGROUND
* In this release we update the Helm repo URL. The underlying repository is still the same, but we have since migrated to using the [Helm chart releaser action](https://helm.sh/docs/howto/chart_releaser_action/) to automate the tagging and releasing of the 1Password/op-scim-bridge chart.

-----------------------------------------------------------------------

## Changes
* Update `1password/op-scim-bridge` Chart URL and version
* Rename some of the variables in `deploy.sh` for clarity
* Introduce additional variables in `deploy.sh` for clarity
* Chart includes [1Password SCIM bridge v2.4.1](https://app-updates.agilebits.com/product_history/SCIM#v204011)
* Chart includes dependency bitnami/redis v16.13.2 (i.e. redis v6.2.7)
* Note that we are no longer keeping the 1password/op-scim-bridge Chart version and SCIM bridge app version in lockstep. For example, the chart version for this release is 2.5.0 and the app version is 2.4.1.

-----------------------------------------------------------------------

## Checklist
- [x] review the [contributing doc](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md) with steps for both adding or updating your application (if applicable)
------------------------------------------------------------------------

Reviewer: @marketplace-eng

### CODE REVIEW

**Comment by devillexio** [comment]
Hi @keladhruv and @bikram20. I know I only submitted this PR yesterday, but I would really appreciate a review.

I'm trying to fix an issue affecting our latest release on the Digital Ocean Marketplace. The particular issue is fixed in the release included in this PR. 🙏

**Comment by devillexio** [comment]
Hi folks. It's been just under a week since we created this PR. Can we please get an ETA for when you think it will be reviewed?

**Comment by devillexio** [comment]
I've created a DO support ticket ([MAR-3373](https://lifebuoy.atlassian.net/servicedesk/customer/portal/1/MAR-3373)) to ask for an update and potential ETA.

**Review by bikram20 — APPROVED** [review]

**Comment by bikram20** [comment]
@devillexio Can you please make sure to test the merged 1-click?

**Comment by devillexio** [comment]
@bikram20, I did test the changes using the updated `deploy.sh`, but I will also test it via the marketplace app once updated.

**Pull request merged**
