### PR TITLE
Tekton Pipelines v0.29.0 (via kapp-controller)

### PR DESCRIPTION
**Pull request by linkdd**
## BACKGROUND

[Tekton](https://tekton.dev) is a Cloud Native Continuous Integration operator for Kubernetes.

No official Helm chart exist to deploy it, therefore this stack rely on [kapp-controller](https://carvel.dev/kapp-controller) to keep track of the deployed resources (for upgrades/uninstall) (see PR #270).

A new namespace `kapp-tekton` contains the resources required to deploy Tekton:

 - a ServiceAccount `kapp-deployer`
 - an `App` resource to deploy the official YAML manifest via the kapp-controller

A ClusterRoleBinding of the role `cluster-admin` to the `kapp-deployer` ServiceAccount is also created to allow `kapp-controller` to create the resources listed in the official manifest.

Upon uninstall, the App resource is deleted, then the ClusterRoleBinding, and finally the namespace `kapp-tekton`.

-----------------------------------------------------------------------

## Changes
* Add a new stack `tekton-pipelines`
* Add a `deploy.sh` and an `uninstall.sh` script
* Add a default `app.yml` manifest to deploy the resources described above

-----------------------------------------------------------------------

## Checklist
- [x] review the [contributing doc](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md) with steps for both adding or updating your application (if applicable)
------------------------------------------------------------------------

Reviewer: @marketplace-eng

### CODE REVIEW

**Comment by lottetreg** [comment]
Hi @linkdd—thank you for your pull request! Just a few comments:

1. When I run `kubectl get events -wA` during deploying I see some warnings—are those expected?
```
kapp-controller   0s          Normal    ScalingReplicaSet         deployment/kapp-controller              Scaled up replica set kapp-controller-5d9479fbfb to 1
kapp-controller   0s          Normal    SuccessfulCreate          replicaset/kapp-controller-5d9479fbfb   Created pod: kapp-controller-5d9479fbfb-d6gkh
kapp-controller   0s          Normal    Scheduled                 pod/kapp-controller-5d9479fbfb-d6gkh    Successfully assigned kapp-controller/kapp-controller-5d9479fbfb-d6gkh to test-tekton-default-pool-ujiva
kapp-controller   0s          Normal    Pulling                   pod/kapp-controller-5d9479fbfb-d6gkh    Pulling image "index.docker.io/k14s/kapp-controller@sha256:48fd422e98ce67dbec2d2d908488816ee6cbae8abdbb7eef1f3892306219c040"
kapp-controller   0s          Normal    Pulled                    pod/kapp-controller-5d9479fbfb-d6gkh    Successfully pulled image "index.docker.io/k14s/kapp-controller@sha256:48fd422e98ce67dbec2d2d908488816ee6cbae8abdbb7eef1f3892306219c040" in 16.007563712s
kapp-controller   0s          Normal    Created                   pod/kapp-controller-5d9479fbfb-d6gkh    Created container kapp-controller
kapp-controller   0s          Normal    Started                   pod/kapp-controller-5d9479fbfb-d6gkh    Started container kapp-controller
tekton-pipelines   0s          Normal    ScalingReplicaSet         deployment/tekton-pipelines-controller   Scaled up replica set tekton-pipelines-controller-67b4676f7 to 1
tekton-pipelines   0s          Normal    ScalingReplicaSet         deployment/tekton-pipelines-webhook      Scaled up replica set tekton-pipelines-webhook-7b74995c8b to 1
tekton-pipelines   0s          Normal    SuccessfulCreate          replicaset/tekton-pipelines-controller-67b4676f7   Created pod: tekton-pipelines-controller-67b4676f7-rnsws
tekton-pipelines   0s          Normal    Scheduled                 pod/tekton-pipelines-controller-67b4676f7-rnsws    Successfully assigned tekton-pipelines/tekton-pipelines-controller-67b4676f7-rnsws to test-tekton-default-pool-ujiv6
tekton-pipelines   0s          Normal    SuccessfulCreate          replicaset/tekton-pipelines-webhook-7b74995c8b     Created pod: tekton-pipelines-webhook-7b74995c8b-ksxcf
tekton-pipelines   0s          Normal    Scheduled                 pod/tekton-pipelines-webhook-7b74995c8b-ksxcf      Successfully assigned tekton-pipelines/tekton-pipelines-webhook-7b74995c8b-ksxcf to test-tekton-default-pool-ujiva
tekton-pipelines   0s          Warning   FailedMount               pod/tekton-pipelines-controller-67b4676f7-rnsws    MountVolume.SetUp failed for volume "config-logging" : failed to sync configmap cache: timed out waiting for the condition
tekton-pipelines   0s          Warning   FailedMount               pod/tekton-pipelines-controller-67b4676f7-rnsws    MountVolume.SetUp failed for volume "config-registry-cert" : failed to sync configmap cache: timed out waiting for the condition
tekton-pipelines   0s          Warning   FailedMount               pod/tekton-pipelines-controller-67b4676f7-rnsws    MountVolume.SetUp failed for volume "kube-api-access-hq8gs" : failed to sync configmap cache: timed out waiting for the condition
tekton-pipelines   0s          Normal    Pulling                   pod/tekton-pipelines-webhook-7b74995c8b-ksxcf      Pulling image "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.29.0@sha256:46d5b90a7f4e9996351ad893a26bcbd27216676ad4d5316088ce351fb2c2c3dd"
tekton-pipelines   0s          Normal    Pulling                   pod/tekton-pipelines-controller-67b4676f7-rnsws    Pulling image "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.29.0@sha256:72f79471f06d096cc53e51385017c9f0f7edbc87379bf415f99d4bd11cf7bc2b"
tekton-pipelines   0s          Normal    Pulled                    pod/tekton-pipelines-webhook-7b74995c8b-ksxcf      Successfully pulled image "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.29.0@sha256:46d5b90a7f4e9996351ad893a26bcbd27216676ad4d5316088ce351fb2c2c3dd" in 1.93616091s
tekton-pipelines   0s          Normal    Created                   pod/tekton-pipelines-webhook-7b74995c8b-ksxcf      Created container webhook
tekton-pipelines   0s          Normal    Pulled                    pod/tekton-pipelines-controller-67b4676f7-rnsws    Successfully pulled image "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.29.0@sha256:72f79471f06d096cc53e51385017c9f0f7edbc87379bf415f99d4bd11cf7bc2b" in 1.7828438s
tekton-pipelines   0s          Normal    Started                   pod/tekton-pipelines-webhook-7b74995c8b-ksxcf      Started container webhook
tekton-pipelines   0s          Normal    Created                   pod/tekton-pipelines-controller-67b4676f7-rnsws    Created container tekton-pipelines-controller
tekton-pipelines   0s          Normal    Started                   pod/tekton-pipelines-controller-67b4676f7-rnsws    Started container tekton-pipelines-controller
tekton-pipelines   0s          Warning   FailedGetResourceMetric   horizontalpodautoscaler/tekton-pipelines-webhook   failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
tekton-pipelines   0s          Warning   FailedComputeMetricsReplicas   horizontalpodautoscaler/tekton-pipelines-webhook   invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
tekton-pipelines   0s          Warning   FailedGetResourceMetric        horizontalpodautoscaler/tekton-pipelines-webhook   failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
```
2. Can you please make both the deploy.sh and uninstall.sh scripts executable?
3. Should uninstall.sh also destroy `kapp-controller`?
4. How does upgrading work with `kapp-controller`? (Just checking that you don't need an upgrade.sh)

Our team is out for the rest of the week, but we'll be back next week to address your changes. Thank you!

**Comment by linkdd** [comment]
Hi @lottetreg, thanks for the feedback!

 1. I'll have to take a look later this week to make sure this is normal.
 I think the 3 `FailedMount` are because the `ConfigMap` was not yet created by kapp-controller (this can be fixed by applying some labels provided by `kapp` for ordering).
 The ones about the metrics may be because there is no metric-server configured?
 2. Damn you Windows, I always forget 😄 
 3. Honestly, I don't think so. I made the PR to `kapp-controller` to give the ability to deploy softwares without Helm (because not every upstream provide one), so this will be used by other stacks in the future (I hope, at least the ones I plan to add)
 4. `kapp-controller` relies on [kapp](https://carvel.dev/kapp) and periodically fetch the source to reconcile it.
 When `kapp` deploy resources, it labels them to keep track of what has been deployed, if the new YAML manifest change, `kapp` will detect them during its `diff` phase and act accordingly during its `apply` phase.
 If I used the `latest` version of the Tekton YAML manifest, `kapp-controller` would automatically update it whenever it changes (not what you want in production).
 If I change the version in the `app.yml` file, same thing will happen, `kapp-controller` will automatically update it.
 Therefore, the `upgrade.sh` script would be identical to the `deploy.sh`, does it still need to be provided?

**Review by keladhruv — CHANGES_REQUESTED** [review]
Hi @linkdd!

Sorry for getting back to you late, everything looks good, just one change  -
-  Can you make the `deploy.sh` , `upgrade.sh` and `uninstall.sh` file executable?

Thanks!

**Comment by linkdd** [comment]
@keladhruv Happy new year :tada:

> Sorry for getting back to you late

No worries, I guess there is a lot to do at DigitalOcean 🙂

> Can you make the `deploy.sh` , `upgrade.sh` and `uninstall.sh` file executable?

Done in last commit (damn you Windows, I always forget this, whish there would be an option in the `.gitattributes` file to automate this).

**Review by keladhruv — APPROVED** [review]
LGTM

**Pull request merged**
