### PR TITLE
Fyipe

### PR DESCRIPTION
**Pull request by nawazdhandala**
## BACKGROUND
Fyipe is one complete DevOps and IT Ops platform. 

Fyipe lets you do: 

**Monitoring:** Monitors your website, web apps, APIs, servers and more and give you detailed metrics of things that might be wrong with your infrastructure. 

**Status Page:** Fyipe gives you a beautiful and customizable status page for your online business which helps improve transparency with your customers and cuts support costs.

**Tests:** Write automated tests for your website, API's and more and know instantly when they start failing. 

**On-Call and Incident Management:** On-Call Management lets you alert the right team at the right time saving you critical time during downtime.

**Performance Monitoring:** Monitor the performance of your apps, servers, APIs, and more and alert your team when any of your performance metrics degrades.

**Website:** https://fyipe.com

-----------------------------------------------------------------------

## Changes
- Added a new Fyipe App (Helm Chart & K8s yaml)

-----------------------------------------------------------------------

## Checklist
- [ Checked ] review the [contributing doc](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md) with steps for both adding or updating your application (if applicable)
------------------------------------------------------------------------

Reviewer: @marketplace-eng

### CODE REVIEW

**Comment by arosales** [comment]
@nawazdhandala Welcome to the DigitalOcean community, and your Kubernetes 1-click submission. We will be reviewing Fyipe shortly.

**Comment by paulanunda** [comment]
Hi @nawazdhandala, I was able to install the app successfully, but how do I log in? Do I need to create an account, or does this ship with default credentials?

**Comment by nawazdhandala** [comment]
@paulanunda  Yes, you need to sign up for a new account.

**Comment by nawazdhandala** [comment]
@paulanunda Any updates on when this will be published to the marketplace?

**Comment by scottcrawford03** [comment]
hey @nawazdhandala! have you had a chance to fill out https://docs.google.com/forms/d/1fzbOUYTMXbrn9cECEZA6ya0zITcdCWtpJWHfkxmsWAQ yet so we can have more info for the listing? thanks!

**Comment by nawazdhandala** [comment]
@scottcrawford03  I think I filled that up last week as soon as I created this PR. It's with do@fyipe.com email. Please let me know if you do not find it and I'll resubmit the form again.

**Comment by scottcrawford03** [comment]
@nawazdhandala ah I see it now. It's under Hackerbay, inc. Sorry for missing that! working on it now!

**Comment by nawazdhandala** [comment]
@scottcrawford03 Thank you for letting me know. :)

**Comment by scottcrawford03** [comment]
@nawazdhandala you should see it live now!

**Comment by nawazdhandala** [comment]
@scottcrawford03  Thank you so much. Looks perfect! :)

**Comment by nawazdhandala** [comment]
@scottcrawford03 How do we make it show up here https://marketplace.digitalocean.com/category/kubernetes? and few other categories like Analytics, Dev Tools, Monitoring, Logging?

**Comment by scottcrawford03** [comment]
@nawazdhandala I'll update the categories on our side

**Comment by nawazdhandala** [comment]
@scottcrawford03 Thank you! :)

**Pull request merged**
