### PR TITLE
Commit on Ondat-first-pr

### PR DESCRIPTION
**Pull request by chris-milsted**
## BACKGROUND
* Add information about the background and reason for the change.

Adding in the Ondat storage to the marketplace. Depricated the legacy storageos offering

-----------------------------------------------------------------------

## Changes
* List the changes that you made
created new stack for ondat.
-----------------------------------------------------------------------

## Checklist
- [x] review the [contributing doc](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md) with steps for both adding or updating your application (if applicable)
------------------------------------------------------------------------

Reviewer: @marketplace-eng

### CODE REVIEW

**Comment by bikram20** [comment]
@v-ctiutiu Please plan to review this.

**Review by v-ctiutiu — CHANGES_REQUESTED** [review]
I tested all the scripts and everything works just fine. I also used the manifests from the [sa-demo-ondat](https://github.com/chris-milsted/sa-demo-ondat/tree/main/pvc) repo to test the setup and everything seems to be ok.

I found something odd, though. Not quite related to this PR, but maybe it's something to take into account. If I use below scenario, I am not able to successfully reinstall the Ondat Helm chart. The steps to reproduce are as follows:

1. Install the StorageOS suite using the `kubectl storageos` plugin as explained [here](https://docs.ondat.io/docs/install/digitalocean-kubernetes/).
2. Test the setup using  [sa-demo-ondat](https://github.com/chris-milsted/sa-demo-ondat/tree/main/pvc) manifests - everything works as expected.
3. Uninstall the StorageOS stack via `kubectl storageos uninstall --include-etcd`.
4. Reinstall the StorageOS stack, but this time via Helm using the `deploy.sh` script from this PR.
5. Check Pods status from the `storageos` namespace via `kubectl get pods -n storageos`. Pods enter in a crash loopback state:
```
NAME                                   READY   STATUS             RESTARTS      AGE
storageos-node-9g26g                   2/3     CrashLoopBackOff   4 (75s ago)   3m3s
storageos-node-zqn75                   2/3     CrashLoopBackOff   4 (70s ago)   3m3s
storageos-scheduler-7fcf5cb9c6-rhbh7   1/1     Running            0             3m14s
```

Looking at the logs of the affected Pods I see:

```json
{"error":"node \"ee062bbd-424d-44ec-a38f-0d2e05a90a6f\" was previously a member of cluster id \"194250dc-19e4-4b84-83fc-713eb49dc3ab\", tried to join another cluster (\"4c1e62a9-5aee-4ac9-ad92-e77dfad746df\") - aborting startup. To delete all data on the node and join the new cluster, remove the \"/var/lib/storageos/config.json\" directory. To recover this node data, please contact support.","level":"error","msg":"failed to initialise local node","time":"2022-06-17T14:21:51.140631739Z"}
```

For me, it seems that something stays in the etcd database from the previous installation (kubectl storageos plugin) which causes things to break. But, I may be wrong.

@chris-milsted can you try above scenario and tell me if it reproduces on your end as well ? Thanks.

**Comment by v-ctiutiu** [comment]
> I tested all the scripts and everything works just fine. I also used the manifests from the [sa-demo-ondat](https://github.com/chris-milsted/sa-demo-ondat/tree/main/pvc) repo to test the setup and everything seems to be ok.
> 
> I found something odd, though. Not quite related to this PR, but maybe it deserves some attention. If I use below scenario, I am not able to successfully reinstall the Ondat Helm chart. The steps to reproduce are as follows:
> 
> 1. Install the StorageOS suite using the `kubectl storageos` plugin as explained [here](https://docs.ondat.io/docs/install/digitalocean-kubernetes/).
> 2. Test the setup using  [sa-demo-ondat](https://github.com/chris-milsted/sa-demo-ondat/tree/main/pvc) manifests - everything works as expected.
> 3. Uninstall the StorageOS stack via `kubectl storageos uninstall --include-etcd`.
> 4. Reinstall the StorageOS stack, but this time via Helm using the `deploy.sh` script from this PR.
> 5. Check Pods status from the `storageos` namespace via `kubectl get pods -n storageos`. Pods enter in a crash loopback state:
> 
> ```
> NAME                                   READY   STATUS             RESTARTS      AGE
> storageos-node-9g26g                   2/3     CrashLoopBackOff   4 (75s ago)   3m3s
> storageos-node-zqn75                   2/3     CrashLoopBackOff   4 (70s ago)   3m3s
> storageos-scheduler-7fcf5cb9c6-rhbh7   1/1     Running            0             3m14s
> ```
> 
> Looking at the logs of the affected Pods I see:
> 
> ```json
> {"error":"node \"ee062bbd-424d-44ec-a38f-0d2e05a90a6f\" was previously a member of cluster id \"194250dc-19e4-4b84-83fc-713eb49dc3ab\", tried to join another cluster (\"4c1e62a9-5aee-4ac9-ad92-e77dfad746df\") - aborting startup. To delete all data on the node and join the new cluster, remove the \"/var/lib/storageos/config.json\" directory. To recover this node data, please contact support.","level":"error","msg":"failed to initialise local node","time":"2022-06-17T14:21:51.140631739Z"}
> ```
> 
> For me, it seems that something stays in the etcd database from the previous installation (kubectl storageos plugin) which causes things to break. But, I may be wrong.
> 
> @chris-milsted can you try above scenario and tell me if it reproduces on your end as well ? Thanks.

@chris-milsted Please disregard above comment - this is expected and related to how storageos works, so my bad. More details can be found [here](https://docs.ondat.io/docs/operations/uninstall/).

**Review by bikram20 — APPROVED** [review]

**Comment by bikram20** [comment]
@v-ctiutiu I know you spent some time on Ondat. Are you good with the PR?

**Comment by v-ctiutiu** [comment]
> @v-ctiutiu I know you spent some time on Ondat. Are you good with the PR?

@bikram20 Yes, except for the missing new line at the end of the Helm values file. It's a minor thing, but may cause issues in some systems.

**Review by v-ctiutiu — APPROVED** [review]

**Pull request merged**
