### PR TITLE
Update 1Password SCIM bridge to v2.1.0

### PR DESCRIPTION
**Pull request by devillexio**
## BACKGROUND
* 1Password SCIM bridge v2.1.0 was released and we are updating our downstream applications.

-----------------------------------------------------------------------

## Changes
* Update helm chart from v2.0.2 to v2.1.0 

-----------------------------------------------------------------------

## Checklist
- [x] review the [contributing doc](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md) with steps for both adding or updating your application (if applicable)
- [x] Minimum [resource requirements](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md#adding-your-application) for your application are up to date. We use this information to prevent applications from being installed on undersized clusters.
------------------------------------------------------------------------

Reviewer: @marketplace-eng

### CODE REVIEW

**Comment by devillexio** [comment]
The Minimum Resource Requirements seem to be a recent addition to the PR Checklist.

cc @alicethorne-ab

**Comment by keladhruv** [comment]
@devillexio 
Thanks for updating 1Password to a newer version!
Please check out the sample [do_config.yml](https://github.com/digitalocean/marketplace-kubernetes/blob/master/stacks/helm3-test/do_config.yml) file to add resource requirements.

**Review by keladhruv — APPROVED** [review]
LGTM

**Comment by keladhruv** [comment]
Your PR is now merged, please update the version on [vendor portal](https://cloud.digitalocean.com/vendorportal/) so that your changes get reflected on [DigitalOcean Marketplace](https://marketplace.digitalocean.com/apps/1password-scim-bridge)

**Pull request merged**
