### PR TITLE
add chatwoot

### PR DESCRIPTION
**Pull request by vishnu-narayanan**
## BACKGROUND

[Chatwoot](https://github.com/chatwoot/chatwoot) is an open-source customer engagement suite, an alternative to the likes of Intercom, Zendesk, Salesforce Service Cloud, etc. Chatwoot gives an integrated view of conversations happening in different communication channels. It supports the following conversation channels at the moment. Live chat from website, Facebook, Twitter, Whatsapp, SMS, MMS, API(Channel), Email, Line, Telegram, and many more in the works. 

This stack installs Chatwoot along with all the respective dependencies as a 1-click k8s app. After the deployment, users can access the web UI and start using Chatwoot.

Ref: 
1. Website  - https://chatwoot.com
2. Github    - https://github.com/chatwoot
-----------------------------------------------------------------------

## Changes

* add chatwoot

-----------------------------------------------------------------------

## Checklist
- [x]  review the [contributing doc](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md) with steps for both adding or updating your application (if applicable)
------------------------------------------------------------------------

Reviewer: @marketplace-eng

### CODE REVIEW

**Comment by jgannondo** [comment]
Thanks for the PR! We'll review it soon :)

**Review by keladhruv — APPROVED** [review]
LGTM

**Comment by jgannondo** [comment]
@vishnu-narayanan Hi! Quick question. In marketplace.digitalocean.com/apps/chatwoot it says:

```After deploying the Chatwoot, navigate to the IP address of the load balancer created by Kubernetes using your web browser

How can the user find the IP address of the load balancer?

**Comment by vishnu-narayanan** [comment]
@jgannondo Hey,

The user will be able to find the IP address in two ways
1. Use `kubectl` to get the load balancer IP for `chatwoot` service. (https://github.com/chatwoot/charts/blob/main/charts/chatwoot/templates/NOTES.txt)
2. Use the K8s dashboard from their DigitalOcean cluster page.

**Pull request merged**
