### PR TITLE
1Password SCIM bridge version bump to 2.1.2

### PR DESCRIPTION
**Pull request by grellyd**
## BACKGROUND
* Bump the 1Password SCIM bridge to v2.1.2

-----------------------------------------------------------------------

## Changes
* https://app-updates.agilebits.com/product_history/SCIM#v201022

-----------------------------------------------------------------------

## Checklist
- [x] review the [contributing doc](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md) with steps for both adding or updating your application (if applicable)
------------------------------------------------------------------------

Reviewer: @marketplace-eng

### CODE REVIEW

**Review by bradford-hamilton — APPROVED** [review]
Lgtm, thanks!

**Comment by jgannondo** [comment]
@grellyd this will go into production once you update the PR in the Vendor Portal. (We'll automate this response shortly so there won't be a delay, sorry about that!)

**Comment by grellyd** [comment]
> @grellyd this will go into production once you update the PR in the Vendor Portal. (We'll automate this response shortly so there won't be a delay, sorry about that!)

Huh I could have sworn I pressed 'submit' on the Vendor portal update. Let's try that again.

**Comment by grellyd** [comment]
Looks like that went through. Thanks for the bump @jgannondo

**Pull request merged**
