### PR TITLE
adding kotal stack

### PR DESCRIPTION
**Pull request by mabdulmoghni**
## BACKGROUND
* Adding Kotal stack to DO Marketplace

-----------------------------------------------------------------------

## Changes
* adding required changes and deployment files under stacks/kotal directory

-----------------------------------------------------------------------

## Checklist
- [ ] review the [contributing doc](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md) with steps for both adding or updating your application (if applicable)
------------------------------------------------------------------------

Reviewer: @marketplace-eng

### CODE REVIEW

**Comment by mbeyt** [comment]
When running deploy.sh, it hangs indefinitely, and when installing directly through helm, it returns the following error: 
```
kotal git:(kotal) helm install kotal kotal/kotal

Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install:
PersistentVolumeClaim "kotal-traefik" in namespace "traefik" exists and cannot be imported into the current release: invalid 
ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "default": current value is 
"kotal"
```
Please take a look and address this.

**Comment by mabdulmoghni** [comment]
Just tried to install the chart with the deploy.sh script on a k8s cluster running on DO and it succeeded.

I am afraid you're installing it on a local private k8s cluster.
When it hangs indefinitely, Most probably it's waiting for a resource creation. in the local k8s cluster case, i believe it's waiting for the ingress controller's public LoadBalancer/Public IP creation ... and will fail after the 8m0s timeout configured in the deploy.sh script.
If so, and for testing only, you can run below CMD in another terminal. just to add an IP manually while installing the chart on a local cluster
$ kubectl patch svc kotal-traefik -n traefik -p '{"spec": {"type": "LoadBalancer", "externalIPs":["172.31.71.218"]}}'

Also, if you want to test helm chart installation directly, please make sure to install it in the 'kotal' namespace.
Install it with this CMDs
$ helm repo add kotal https://kotalco.github.io/kotal-helm-chart
$ helm repo update > /dev/null
$ helm upgrade kotal kotal/kotal --install --namespace kotal --create-namespace

Please give it another try and let me know if you have any question.
Thanks.

**Comment by mabdulmoghni** [comment]
Hey @mbeyt Please let me know if you managed to install it or if you need anything from my side.

**Comment by mFarghaly** [comment]
Hi @mbeyt @keladhruv  Can you please review our PR, it has been **2 weeks**.
If you need any help, please let us know.
We can show you how we install Kotal using `helm install` on DigitalOcean and other cloud providers.

This is my Calendly link https://calendly.com/kotal/30min if you want to have a meeting anytime.

**Comment by mbeyt** [comment]
We've successfully installed now, so I'm approving and merging this, but please add something to the readme on the listing about it potentially taking up to 8 minutes to run so users are aware. Thank you!

**Review by mbeyt — APPROVED** [review]

**Pull request merged**
