### PR TITLE
add lakefs

### PR DESCRIPTION
**Pull request by johnnyaug**
## BACKGROUND
* Add information about the background and reason for the change.
Add lakeFS app to marketplace
-----------------------------------------------------------------------

## Changes
* List the changes that you made
Add lakeFS app to marketplace
-----------------------------------------------------------------------

## Checklist
- [x] review the [contributing doc](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md) with steps for both adding or updating your application (if applicable)
------------------------------------------------------------------------

Reviewer: @marketplace-eng

### CODE REVIEW

**Comment by lottetreg** [comment]
Hey @johnnyaug! I just have a couple of questions for you.

1.  We saw there aren't any persisted volumes with LakeFS and wanted to confirm that that's expected.
2. Is there anything missing from `stacks/lakefs/values.yml` that would ensure a first-time user of this app has a good experience?

**Comment by johnnyaug** [comment]
@lottetreg thank you for your response.
LakeFS does not use volumes, it should use a separate Postgres instance, and an object storage (e.g. S3).

However, the default installation of lakeFS is for learning purposes and does not persist data, so it uses local storage on the container instead. That's also the reason why there are no values in the `values.yaml` file.

**Review by amilcaru123 — APPROVED** [review]

**Comment by lottetreg** [comment]
@johnnyaug Thanks for the info—that sounds good.

**Review by lottetreg — APPROVED** [review]

**Comment by MattIPv4** [comment]
Hey, @johnnyaug  - Thanks a ton for this! 😄

Would you please shoot me an email when you get a chance?
mcowley at digitalocean dot com 🎉

**Pull request merged**
