### PR TITLE
Cloudcasav2.0.0

### PR DESCRIPTION
**Pull request by nitishdsharma**
## BACKGROUND
* Add information about the background and reason for the change.
-----------------------------------------------------------------------
Cloudcasa Version 2.0.0

## Changes
* List the changes that you made
-----------------------------------------------------------------------
1. Added support for Backup on Azure.
2. Added support for snapshot copy.

## Checklist
- [ ] review the [contributing doc](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md) with steps for both adding or updating your application (if applicable)
------------------------------------------------------------------------

Reviewer: @marketplace-eng

### CODE REVIEW

**Comment by nitishdsharma** [comment]
@pachadotdev 
Can you please review this PR.
Thanks.

**Review by keladhruv — APPROVED** [review]

**Comment by nitishdsharma** [comment]
@keladhruv Thanks for reviewing and merging the PR. How much time would it take to display the changes on One-click application because I can still see v1.0 displayed on DigitalOCean Marketplace one click apps.

**Comment by keladhruv** [comment]
Hi @nitishdsharma ,
Please update the vendor portal with the version!
Once that is done, it should take about 10 mins. 
Thanks!

**Comment by nitishdsharma** [comment]
> Hi @nitishdsharma ,
> Please update the [vendor portal](https://marketplace.digitalocean.com/vendorportal) with the version!
> Once that is done, it should take about 10 mins.
> Thanks!

Hi Dhruv,

Thanks for your point. We have updated the vendor portal and waiting for the changes to reflect on marketplace.

**Pull request merged**
